[web]
3.6.38.70 ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/c/Users/KumaresanPeriyannan/Desktop/terraform-hero/ansible/kumar-new.pem

[db]
13.201.62.84  ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/c/Users/KumaresanPeriyannan/Desktop/terraform-hero/ansible/kumar-new.pem
